---
- name: image jenkins
  docker_container:
    hostname: jenkins.michaeljenkins.org
    name: jenkins
    image: jenkins/jenkins
    env: TZ=Europe/Paris
    volumes:
     - "/srv/docker/jenkins/jenkins-data:/var/jenkins_home"
    state: started
    restart: yes
    ports:
     - 8080:8080
     - 5000:5000